authentication:  # pour login bd ou ldap seul
  is_secure: false #

meeting:
  is_secure: false

auth:
  is_secure: false

doc:
  is_secure: true
  credentials: [[member, invite]]

all:
  is_secure: true
  credentials: [[member]]
